const { test, expect } = require('@playwright/test');

test('standalone Loyalty: enrol, award, claim, refund, fulfil and retain access', async ({ page, browser }) => {
  await page.goto('/loyalty-app');
  await page.getByRole('button', { name: 'Create a Loyalty account', exact: true }).click();
  await page.getByLabel('Your name', { exact: true }).fill('Loyalty Owner');
  await page.getByLabel('Business name').fill('Independent Loyalty Club');
  await page.getByLabel('Email', { exact: true }).fill(`loyalty-${Date.now()}@example.com`);
  await page.getByLabel('Password (12–72 characters)').fill('loyalty-owner-password');
  await page.getByRole('button', { name: 'Create Loyalty account', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Independent Loyalty Club', exact: true })).toBeVisible();
  await page.getByLabel('Open member enrolment').check();
  await page.getByRole('button', { name: 'Save program settings' }).click();
  await expect(page.getByRole('status')).toHaveText('Program settings saved.');
  await page.getByLabel('Reward name', { exact: true }).fill('House coffee');
  await page.getByLabel('Reward cost in points').fill('100');
  await page.getByRole('button', { name: 'Save reward', exact: true }).click();
  await expect(page.getByRole('status')).toHaveText('Reward saved.');
  const url = new URL(await page.getByRole('link', { name: 'Open member portal' }).getAttribute('href'), page.url()).href;
  const memberContext = await browser.newContext({ viewport: { width: 390, height: 844 } });
  const member = await memberContext.newPage();
  await member.goto(new URL('/members', url).href);
  await expect(member.getByRole('heading', { name: 'Open your venue’s rewards' })).toBeVisible();
  await expect(member.getByLabel('Password', { exact: true })).toHaveCount(0);
  await member.getByLabel('Venue code').fill('https://example.com');
  await member.getByRole('button', { name: 'Continue to my venue' }).click();
  await expect(member.getByRole('alert')).toContainText('Enter the venue code');
  await member.getByLabel('Venue code').fill(new URL(url).pathname.split('/').pop());
  await member.getByRole('button', { name: 'Continue to my venue' }).click();
  await expect(member).toHaveURL(url);
  await member.getByRole('button', { name: 'Join this program', exact: true }).click();
  await member.getByLabel('Your name', { exact: true }).fill('Pilot Member');
  await member.getByLabel('Email', { exact: true }).fill(`member-${Date.now()}@example.com`);
  await member.getByLabel('Password (12–72 characters)').fill('loyalty-member-password');
  await member.getByLabel('I accept the program terms').check();
  await member.getByRole('button', { name: 'Join program', exact: true }).click();
  await expect(member.getByRole('heading', { name: '0 points', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Search', exact: true }).click();
  await page.getByRole('button', { name: 'Manage Pilot Member', exact: true }).click();
  await page.getByLabel('Points adjustment (negative to deduct)').fill('250');
  await page.getByLabel('Adjustment reason / receipt reference').fill('Receipt 001');
  await page.getByRole('button', { name: 'Record points adjustment' }).click();
  await expect(page.getByRole('status')).toHaveText('Points adjustment recorded.');
  await member.getByRole('button', { name: 'Refresh membership' }).click();
  await expect(member.getByRole('heading', { name: '250 points', exact: true })).toBeVisible();
  await member.getByRole('button', { name: 'Claim House coffee', exact: true }).click();
  await member.getByRole('button', { name: 'Confirm reward claim', exact: true }).click();
  await expect(member.getByRole('heading', { name: '150 points', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Refresh claims', exact: true }).click();
  await page.getByRole('button', { name: 'Cancel and refund points', exact: true }).click();
  await page.getByRole('button', { name: 'Confirm reward action' }).click();
  await expect(page.getByRole('status')).toHaveText('Reward claim updated.');
  await member.getByRole('button', { name: 'Refresh membership' }).click();
  await expect(member.getByRole('heading', { name: '250 points', exact: true })).toBeVisible();
  await member.getByRole('button', { name: 'Claim House coffee', exact: true }).click();
  await member.getByRole('button', { name: 'Confirm reward claim', exact: true }).click();
  await expect(member.getByRole('heading', { name: '150 points', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Refresh claims', exact: true }).click();
  await page.getByRole('button', { name: 'Fulfil reward', exact: true }).click();
  await page.getByRole('button', { name: 'Confirm reward action' }).click();
  await expect(page.getByRole('status')).toHaveText('Reward claim updated.');
  await page.getByRole('button', { name: 'Cancel Loyalty trial', exact: true }).click();
  await page.getByRole('button', { name: 'Confirm trial cancellation', exact: true }).click();
  await expect(page.getByText('New enrolments, points changes and reward claims are paused.', { exact: false })).toBeVisible();
  await member.reload();
  await expect(member.getByRole('heading', { name: '150 points', exact: true })).toBeVisible();
  await expect(member.getByRole('button', { name: 'Claim House coffee', exact: true })).toBeDisabled();
  const downloaded = member.waitForEvent('download');
  await member.getByRole('button', { name: 'Export my data', exact: true }).click();
  expect((await downloaded).suggestedFilename()).toBe('nua-membership-export.json');
  await page.screenshot({ path: 'test-results/loyalty-merchant.png', fullPage: true });
  await member.screenshot({ path: 'test-results/loyalty-member-mobile.png', fullPage: true });
  await memberContext.close();
});
